<?php

namespace AppBundle\Repository;

/**
 * FilaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilaRepository extends \Doctrine\ORM\EntityRepository
{
}
