<?php

namespace AppBundle\Repository;

/**
 * FilaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilaRepository extends \Doctrine\ORM\EntityRepository {

    public function buscarFila($busca, $busca2): array {
        $conn = $this->getEntityManager()->getConnection();

        $sql = 'SELECT * FROM t_filas
        WHERE nome LIKE :busca or id = :busca2 and deletar = 0 
        ORDER BY nome ASC';
        $stmt = $conn->prepare($sql);
        $stmt->execute(['busca' => $busca, 'busca2' => $busca2]);

        return $stmt->fetchAll();
    }

    public function alterarFila($id, $nome, $status) {
        $conn = $this->getEntityManager()->getConnection();

        $sql = 'UPDATE t_filas'
                . ' SET nome = :NOME, status_2 = :STATUS'
                . ' WHERE id = :ID';
        $stmt = $conn->prepare($sql);
        $stmt->execute(['ID' => $id, 'NOME' => $nome, 'STATUS' => $status]);

        return $stmt;
    }
    
    public function deletarFila($id) {
        $conn = $this->getEntityManager()->getConnection();

        $sql = 'UPDATE t_filas SET deletar = 1 WHERE id = :ID';
        $stmt = $conn->prepare($sql);
        $stmt->execute(['ID' => $id]);

        return $stmt;
    }

}
