<?php

namespace AppBundle\Repository;

/**
 * SenhaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SenhaRepository extends \Doctrine\ORM\EntityRepository {

    public function pegarSenha($idFila) {
        $conn = $this->getEntityManager()->getConnection();

        $sql = 'SELECT nsenha FROM t_filas
        WHERE id = :ID and deletar = 0';
        $stmt = $conn->prepare($sql);
        $stmt->execute(['ID' => $idFila]);

        return $stmt->fetchAll();
    }
    
    public function atualizarSenha($idFila, $senha) {
        $conn = $this->getEntityManager()->getConnection();
        $novaSenha = $senha + 1;
        $sql = 'UPDATE t_filas
        SET nsenha = :NOVASENHA
        WHERE id = :ID and deletar = 0';
        $stmt = $conn->prepare($sql);
        $stmt->execute(['ID' => $idFila, 'NOVASENHA' => $novaSenha]);
        $count = $stmt->rowCount();
        return $count;
    }

}
