<?php

namespace AppBundle\Repository;

/**
 * SenhaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SenhaRepository extends \Doctrine\ORM\EntityRepository
{
}
