<?php

namespace AppBundle\Repository;

/**
 * ServicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicoRepository extends \Doctrine\ORM\EntityRepository {
    
    public function buscarServico($busca, $busca2, $idFila): array {
        $conn = $this->getEntityManager()->getConnection();

        $sql = 'SELECT * FROM t_servicos
        WHERE nomeServico LIKE :busca and deletar = 0 and t_filas_id = :IDFILA or id = :busca2 and deletar = 0 and t_filas_id = :IDFILA
        ORDER BY nome ASC';
        $stmt = $conn->prepare($sql);
        $stmt->execute(['busca' => $busca, 'busca2' => $busca2, 'IDFILA' => $idFila]);

        return $stmt->fetchAll();
    }
    
    public function alterarServico($id, $sigla, $nome, $descricao, $status) {
        $conn = $this->getEntityManager()->getConnection();

        $sql = 'UPDATE t_servicos'
                . ' SET sigla = :SIGLA, nomeServico = :NOME, descricao = :DESCRICAO, status_2 = :STATUS'
                . ' WHERE id = :ID';
        $stmt = $conn->prepare($sql);
        $stmt->execute(['ID' => $id, 'SIGLA' => $sigla, 'NOME' => $nome, 'DESCRICAO' => $descricao, 'STATUS' => $status]);

        return $stmt;
    }

    public function deletarServico($id) {
        $conn = $this->getEntityManager()->getConnection();

        $sql = 'UPDATE t_servicos SET deletar = 1 WHERE id = :ID';
        $stmt = $conn->prepare($sql);
        $stmt->execute(['ID' => $id]);

        return $stmt;
    }

}
