<?php

namespace AppBundle\Repository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository {

    public function buscarUsuario($busca): array {
        $conn = $this->getEntityManager()->getConnection();

        $sql = 'SELECT * FROM t_usuario
        WHERE nome LIKE :busca or usuario = :busca
        ORDER BY nome ASC';
        $stmt = $conn->prepare($sql);
        $stmt->execute(['busca' => $busca]);

        return $stmt->fetchAll();
    }
    
    public function deletarUsuario($id) {
        $conn = $this->getEntityManager()->getConnection();

        $sql = 'DELETE FROM t_usuario WHERE id = :ID';
        $stmt = $conn->prepare($sql);
        $stmt->execute(['ID' => $id]);

        return $stmt;
    }
    
    public function alterarUsuario($id, $nome, $sobrenome, $usuario, $status, $tipo) {
        $conn = $this->getEntityManager()->getConnection();

        $sql = 'UPDATE t_usuario'
                . ' SET nome = :NOME, sobrenome = :SOBRENOME, usuario = :USUARIO, status_2 = :STATUS, t_tipo_id = :TIPO'
                . ' WHERE id = :ID';
        $stmt = $conn->prepare($sql);
        $stmt->execute(['ID' => $id, 'NOME' => $nome, 'SOBRENOME' => $sobrenome, 'USUARIO' => $usuario, 'STATUS' => $status, 'TIPO' => $tipo]);

        return $stmt;
    }
    
    public function direitos($id) {
        $conn = $this->getEntityManager()->getConnection();

        $sql = 'SELECT * FROM t_tipo WHERE id = :ID';
        $stmt = $conn->prepare($sql);
        $stmt->execute(['ID' => $id]);

        return $stmt->fetch();
    }

}
